fix(operations): use os.lstat() and os.fstat()
Because of:

  File "/src/core/operations.py", line 265, in _get_attr
    stat_result = os.stat(target, follow_symlinks=False)
ValueError: stat: cannot use fd and follow_symlinks together